### PR TITLE
Added Insertion Sort

### PR DESCRIPTION
**Pull request by MatheusMuriel**
Happy Hacktoberfest! 🎃
You can added the `hacktoberfest-accepted` tag on this PR? This will be agile my PR count for me earn my t-shir

### CODE REVIEW

**Comment by poyea** [comment]
The two PRs you submitted look suspicious.. #9. https://gist.github.com/rylev/6906490..

**Review by poyea — CHANGES_REQUESTED** [review]
-

**Comment by MatheusMuriel** [comment]
@poyea  
Why suspicious?? Nowhere in the rules say that the code cant be from internet... 
Yes... I used this gist as a base of my code, but i refined, refactored this code and made unit tests for it...   
So, if this repository is only for 100% handmade codes i will abandon this PR...   
I already completed my 4 PRs to hacktoberfest, i contributed with this repo because i love Elixir Language, i saw this repositorie has very few algorithmns and i think thats very sad, so i wanted to help...

**Comment by frankschmitt** [comment]
I agree with @MatheusMuriel here - why do they "look suspicious" ? That's a strange accusation.
@poyea Can you please clarify what's expected of PR's to this repository? (I've got two PR's waiting for review, as well - if you don't want any PR's, please remove the hacktoberfest label from this repository).

**Pull request merged**
